---
- hosts: ctfd
  remote_user: root
  gather_facts: True

  tasks:
  - name: Workaround docker-compose bug with hardware entropy generator https://github.com/docker/compose/issues/6931
    package: name={{ item }} state=latest
    with_items:
    - rng-tools
    - docker
    - docker-compose

  # TODO to automate lets encrypt
  #snap install core; snap refresh core
  #snap install --classic certbot
  #manual: point dns
  #manual: certbot certonly --standalone
  #manual: cp /etc/letsencrypt/live/h0h0h0day.montrehack.ca/fullchain.pem etc/ssl/
  #manual: cp /etc/letsencrypt/live/h0h0h0day.montrehack.ca/privkey.pem etc/ssl/

  #TODO automate mailgun setup
  #manual: add domain to mailgun
  #manual: configure mailgun SMTP didn't work, API did

  - name: Create destination directory
    file:
      path: "/srv/h0h0h0day"
      state: directory

  - name: Upload docker-compose files
    synchronize:
      src: "../docker-compose.yml"
      dest: "/srv/h0h0h0day/"

  - name: Upload secrets
    synchronize:
      src: "../.env"
      dest: "/srv/h0h0h0day/"

  - name: Upload configuration files
    synchronize:
      src: "../etc"
      dest: "/srv/h0h0h0day/"

  - name: Upload ctfd Dockerfile
    synchronize:
      src: "../ctfd"
      dest: "/srv/h0h0h0day/"
