# -*- mode: ruby -*-
# vi: set ft=ruby :

# read secrets from file
secrets = Hash.new
if File.file?("digitalocean.env")
  array = File.read("digitalocean.env").split("\n")
  array.each do |e|
    unless e.start_with?("#")
      var = e.split("=")
      secrets[var[0]] = var[1]
    end
  end
end

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # local box
  config.vm.box = "ubuntu/bionic64"

  config.vm.define secrets["DO_DROPLET_NAME"]
  config.vm.provider :digital_ocean do |provider, override|
    override.ssh.private_key_path = secrets["DO_SSH_PRIVATE_KEY"]
    override.vm.box = 'digital_ocean'
    override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"

    provider.token = secrets["DO_TOKEN"]
    provider.image = 'ubuntu-18-04-x64'
    provider.region = secrets["DO_REGION"]
    provider.size = secrets["DO_SIZE"]
    provider.ssh_key_name = secrets["DO_SSH_KEY_NAME"]
  end

  # Disable default sync
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # Sync to /srv but with exclusions
  config.vm.synced_folder ".", "/srv", type: "rsync",
    rsync__exclude: [".git/", "digitalocean.env"]

  # docker / docker-compose provisioning
  config.vm.provision "shell", inline: <<-SCRIPT
    if ! type docker >/dev/null; then
        echo -e "\n\n========= installing docker..."
        curl -sL https://get.docker.io/ | sh
        echo -e "\n\n========= installing docker bash completion..."
        curl -sL https://github.com/docker/cli/raw/master/contrib/completion/bash/docker > /etc/bash_completion.d/docker
    fi
    if ! type pip3 >/dev/null; then
        echo -e "\n\n========= installing pip..."
        apt install -y python3-pip
    fi
    if ! type rngtest >/dev/null; then
        # on providers w/o hardware rng, haveged should be used instead
        echo -e "\n\n========= installing entropy generating tool to workaround docker-compose issue..."
        apt install -y rng-tools
    fi
    if ! type docker-compose >/dev/null; then
        echo -e "\n\n========= installing docker-compose..."
        curl -L https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
	chmod a+x /usr/local/bin/docker-compose
        echo -e "\n\n========= installing docker-compose command completion..."
        curl -sL https://raw.githubusercontent.com/docker/compose/$(docker-compose --version | awk 'NR==1{print $NF}')/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose
    fi
  SCRIPT
end
