= Challenges

== Find the Challenge Designer

Flag is the MontréHack slack display name of that person


== Spooky Holidays Weather App

https://spooky-holidays-weather-app.bcj.io/

Web

By Becojo


== The Vault

See `challenges/prog.pyc`

By Olivier Arteau


== PHP Login

Available in this repo: `challenges/php-login`

Managed by docker-compose

Deployed: http://h0h0h0day-xchange.montrehack.ca:8080/

By prolog


== crackme

See `challenges/e9331b009bf88399a43e9f3bd0a4244c`

By axdoomer


== The Second Order

See `challenges/h0h0h0_second_order/`

Managed by docker-compose

Deployed: http://h0h0h0day-xchange.montrehack.ca:2199/

By Barberousse


== 0day stores

0day eCommerce as a service, to sell or buy all the 0days you need: http://ctf-infosec.com

By JFGauron


== North Pole's Server

HTTP: http://h0h0h0day-xchange.montrehack.ca:5000/
FTP: h0h0h0day-xchange.montrehack.ca 5001 (in passive mode)

By KptCheeseWhiz


== North Pole-ynomials

Implemented RLWE! Seems to work so it's s3cure right?

todo: decrypt the ciphertext and get flag :)

By lixtelnis


== In Space, No One Can Hear You Scream

See `challenges/sopa.raw`.

Non, Scream n’est pas juste une série de films...

By stormy


== The Day The Frog Stood Still

See `challenges/froggy/`

Deux flags se cachent dans cet artefact binaire exécutable … les versions Linux et Windows sont identiques.

By stormy


== Too Many Files

## Synopsis

You just found a few weird files, barely encrypted.
A first sight, there are not interesting, but maybe they could protect a flag after all!

See what you can get from them!

//

Vous venez juste de trouver d'étrange fichier à moitié chiffrés.
À première vue, ils ne renferment rien de bien intéressant, mais on vous a laissé entendre qu'ils pourraient refermer un flag !

A vous de voir ce que vous pouvez en tirer ;)


## Content

``` text
14a2350ab113850b37850c7afe905ac2829ab7e9f736d131c58d24ea12dab344  a.ipynb
adb3b165d29e08fb605ef17f743f624da24b3d60637018b0aad86993edc97f72  b.pdf
05889477f0f778b83aedc8c7f7dd16177fd30f112bbf5d4d843a5042f489fcdd  c.bin
```

By yaap


== Xmas Lottery

Cryptography

ncat h0h0h0day-xchange.montrehack.ca 6000

by nospace
