= Challenges

== Find the Challenge Designer

Flag is the MontréHack slack display name of that person


== Spooky Holidays Weather App

https://spooky-holidays-weather-app.bcj.io/

Web

By Becojo


== The Vault

See `challenges/prog.pyc`

By Olivier Arteau


== PHP Login

Available in this repo: `challenges/php-login`

Managed by docker-compose

Deployed: http://h0h0h0day-xchange.montrehack.ca:8080/

By prolog


== crackme

See `challenges/e9331b009bf88399a43e9f3bd0a4244c`

By axdoomer


== The Second Order

See `challenges/h0h0h0_second_order/`

Managed by docker-compose

Deployed: http://h0h0h0day-xchange.montrehack.ca:2199/

By Barberousse


== 0day stores

0day eCommerce as a service, to sell or buy all the 0days you need: http://ctf-infosec.com

By JFGauron


== North Pole's Server

HTTP: http://h0h0h0day-xchange.montrehack.ca:5000/
FTP: h0h0h0day-xchange.montrehack.ca 5001 (in passive mode)

By KptCheeseWhiz


== North Pole-ynomials

TODO


== In Space, No One Can Hear You Scream

See `challenges/sopa.raw`.

Non, Scream n’est pas juste une série de films...

By stormy


== The Day The Frog Stood Still

See `challenges/froggy/`

Deux flags se cachent dans cet artefact binaire exécutable … les versions Linux et Windows sont identiques.

By stormy


