= Flags

== Spooky Holidays Weather App

FLAG-i-hope-no-one-uses-that-gem

== The Vault

FLAG-a420384997c8a1a93d5a84046117c2aa

== PHP Login

FLAG-ThAnKs_Mr_TypE_Juggal0_PhP

== crackme

798969-2009a61e

== The Second Order

  h0h0h0{5omet1me5_N0_SQLi_1s_s7ill_SQLi}

== 0day stores

FLAG-d563f38516aab525552f150dd83110f7

== North Pole's Server

  FLAG{YOURE_GETTING_COAL_THIS_CHRISTMAS}

== North Pole-ynomials

  pol_timez_pol???

== In Space, No One Can Hear You Scream

FLAG-ac67675aae438dfe9cf6f61fc9d81d2

== The Day The Frog Stood Still

* Flag 1 easy: FLAG-eea342a57c9313484e2b73715a5cbdb1
* Flag 2: FLAG-8426aee7ad0218ed27ab80dccc04ff62

== Too Many Files

FLAG_9d9c3a85bcee7de93a2da8c752036c79

== Xmas Lottery

FLAG-RBr1Ryen75o1aZ6NZriap6VopLBZTx3C

== "reverse"

FLAG-CNC-GCODE

== Homme-Brella

FLAG-04B4E8A5AFF726C15FEB5B041B71CE4F

== Ping-It!

FLAG-f0c397a85dd205e2ac413b36f844d91e7cddca28b1702d2483592743c2764988

== Random Art Generator

FLAG-2ac750e5a65dfcca48447d9b74c46831

== 99 Villeray

  FLAG{C99VILLERAYGANGGANG}

== Quote Database

FLAG-qEftt9QMSK65aDMqzwGExuHlmwipZWdh

== Paradise

FLAG-LLtrJ6tbslr3AatOrmPH0Hf30ezP9w6R

== Enemy Hunting Notebook

NOTE: Even more variations were accepted

978bf4e17caec-29d50c68cc458801c7b89641111-0.028

or

Flag - 978bf4e17caec-29d50c68cc458801c7b89641111-0.028

== Santa Claus Login

FLAG-TeTuBinDansTonCotonOuate

== Repas 1

  FLAG{aISbI5MVYm8WW1GZ77HG}

== Repas 2

  FLAG{HOhoHOmotH3rfUXOR3RHohO}

== Gift Ideas 1

FLAG-ug2yahLie2ooh8shuthohng8Quei7Sho

== Gift Ideas 2

FLAG-mohquat3Iesh9Oo1zoo4aeZaidaij0le

== Gift Ideas 3

FLAG-oehahMaeNahb4Oojushohf1uneegoosh

== Gift Ideas 4

FLAG-ceev3sheiYieboonae9ouYai1rooL2tu

== Gift Ideas 5

FLAG-ieviriekaijahhieshai6goh7Lei7phe

== Gift Ideas 6

FLAG-eesiej8ahh2kesh6pheeChoPion4iese

== Filthy Rancid Bacon

FLAGMERRYXMAZYALL

== Voute Native Android

FLAG_NatifPasSecure!

== Speak Friend and Enter

FLAG-692191b797fc6fc3686bcfa8e70e3887

== Mission

FLAG-HummusGuruChangelemondeGoVegan

== Christmas Card

montrehack_loves_you

== Late: Shibe

  FLAG-{heck}
