= README

== Infrastructure

Terraform is deploying resources on Digital Ocean and running Ansible for provisoning.

=== Setup

* Install https://www.terraform.io[terraform]
* Install https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html[Ansible] (>= 2.4)
* Dynamic inventory script in `../lib/ext/` is: https://github.com/nbering/terraform-inventory/blob/master/terraform.py[terraform.py]
* Prepare terraform with: `terraform init`

Put your secrets in `env.sh`:

    export DO_API_TOKEN=<digital ocean api key>
    export TF_VAR_SSH_KEY_FILE=<full path to private disposable key>
    export TF_VAR_DO_SSH_KEY_NAME=<name of the ssh key as imported in digital ocean>

Source it:

    source env.sh

Webhook config is done via `.env` regular docker-compose.yml secret setup.

=== Do it

    terraform plan
    terraform apply

=== Connect

    ansible-ssh -i ../lib/ext/terraform.py ctfd

=== Setup

* DNS creation and assignment is not automated
* Lets encrypt is not automated (see comments in ansible file)
* CTFd must be configured

=== Finish him

    terraform destroy

== CTFd

The Webhook plugin will not trigger if the CTF is not started. An admin cannot
test the plugin by solving a challenge *before* the CTF is open.
