= README

== Infrastructure

Terraform is deploying resources on Digital Ocean and running Ansible for provisoning.

=== Setup

* Install https://www.terraform.io[terraform]
* Install https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html[Ansible] (>= 2.4)
* Prepare terraform with: `terraform init`

Put your secrets in `env.sh`:

    export DO_API_TOKEN=<digital ocean api key>
    export TF_VAR_H0H0_YEAR=<h0h0day year>

Source it:

    source env.sh

Webhook config is done via `.env` regular docker-compose.yml secret setup.

=== Deploy it

Infrastructure via terraform

    cd terraform/
    terraform plan
    terraform apply
    cd ../

Provision via Ansible

    cd ansible/
    ansible-playbook -i inventory.yml update-reboot.yml ctfd.yml challenge.yml
    cd ../

=== Connect

    ./ssh.sh <ctfd|challenge>

=== Setup

* DNS creation and assignment is not automated
* Lets encrypt is not automated (see comments in ansible file)
* CTFd must be configured

=== Finish him

    terraform destroy

== CTFd

The Webhook plugin will not trigger if the CTF is not started. An admin cannot
test the plugin by solving a challenge *before* the CTF is open.
