#!/bin/bash
regex="^-f -e trace=network -s 5000 ping -W 5 -c 1 \b(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]))?(\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]))?(\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]))?\b$"
if [[ $@ =~ $regex ]]; 
then
/usr/bin/strace $@
else
echo 'This is not a supported IP address.'
echo 'We only support IPv4 IP addresses. Sorry IPv6 adventists.'
fi
